# This file stores configurations for your Shopify app.

scopes = "write_products, write_draft_orders, read_orders, read_assigned_fulfillment_orders, read_merchant_managed_fulfillment_orders, read_third_party_fulfillment_orders, write_assigned_fulfillment_orders, write_merchant_managed_fulfillment_orders, write_third_party_fulfillment_orders, read_inventory"
